# Generated by Django 3.1.7 on 2021-02-28 21:06

from django.db import migrations, models
import updater.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESP32',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=512)),
                ('firmware_file', models.IntegerField(null=True, verbose_name=updater.models.Firmware)),
                ('auto_update', models.BooleanField(default=False)),
                ('mac_address', models.CharField(default='00:00:00:00:00', editable=False, max_length=20)),
                ('md5checksum', models.CharField(default='00000000000000000000000000000000', editable=False, max_length=32)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0', editable=False)),
            ],
            options={
                'verbose_name': 'ESP32 Device',
            },
        ),
        migrations.CreateModel(
            name='ESP8266',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=512)),
                ('firmware_file', models.IntegerField(null=True, verbose_name=updater.models.Firmware)),
                ('auto_update', models.BooleanField(default=False)),
                ('device_id', models.IntegerField(editable=False)),
                ('mac_address', models.CharField(default='00:00:00:00:00', editable=False, max_length=20)),
                ('md5checksum', models.CharField(default='00000000000000000000000000000000', editable=False, max_length=32)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0', editable=False)),
            ],
            options={
                'verbose_name': 'ESP8266 Device',
            },
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=265)),
                ('firmware_file', models.FileField(unique=True, upload_to='files/firmware', validators=[updater.models.validate_file])),
                ('file_size', models.IntegerField(editable=False)),
                ('device_type', models.IntegerField(choices=[(8266, 'ESP8266'), (32, 'ESP32')], default=0)),
                ('md5checksum', models.CharField(editable=False, max_length=32)),
            ],
            options={
                'verbose_name': 'Firmware File',
            },
        ),
    ]
