# Generated by Django 3.1.7 on 2021-02-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp32',
            name='firmware_file',
            field=models.IntegerField(null=True),
        ),
    ]
