# Generated by Django 3.2.6 on 2021-08-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0002_auto_20210228_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp32',
            name='firmware_file',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='esp8266',
            name='firmware_file',
            field=models.IntegerField(default=-1),
        ),
    ]
